#!/bin/sh

# Directory containing video files
DIR="."
mkdir COVERS
mkdir AUDIO

# Iterate over each video file in the directory
find "$DIR" -type f \( -iname "*.mp4" -o -iname "*.mkv" -o -iname "*.ogg" -o -iname "*.avi" \) | while read -r video_file; do
    # Get the audio codec using ffprobe
    audio_codec=$(ffprobe -v error -select_streams a:0 -show_entries stream=codec_name -of default=noprint_wrappers=1:nokey=1 "$video_file")

    # Determine the output file extension based on the audio codec
    case "$audio_codec" in
        opus)
            output_file="${video_file%.*}.ogg"
            temp_audio_only="temp_audio_only.ogg"
            ;;
        mp3)
            output_file="${video_file%.*}.mp3"
            temp_audio_only="temp_audio_only.mp3"
            ;;
        aac)
            output_file="${video_file%.*}.m4a"
            temp_audio_only="temp_audio_only.m4a"
            ;;
        *)
            echo "Unsupported audio codec: $audio_codec"
            continue
            ;;
    esac

    # Extract the thumbnail as a JPG file
    thumbnail_file="${video_file%.*}.jpg"
    ffmpeg -i "$video_file" -vframes 1 "COVERS/$thumbnail_file"

    # Extract the audio without re-encoding and copy metadata
    ffmpeg -i "$video_file" -map 0:a -c:a copy -map_metadata 0 -y "AUDIO/$output_file"

done
