#!/bin/sh
# convert all files to JXL and archive the originals

# archive dir
mkdir -p $USER/Backups/Images/originals

# threads
THREADS=$(( $(nproc) - 2 ))

parallel --bar -j "$THREADS" 'gm convert -auto-orient {} {.}.jxl && mv {} $USER/Backups/Images/originals/' ::: *.jpg *.JPG *.jpeg *.JPEG .png .PNG
